feat: implement log forwarding
canonical/sdcore-amf-k8s-operator pull request #96
Opened 2024-02-27 22:29 UTC by gruyaume

# Description

Implement log forwarding via Pebble's new `log-target` spec. We use the `loki_push_api` charm relation to get the loki endpoint.

## Usage

```
juju deploy sdcore-amf-k8s
juju deploy grafana-agent-k8s
juju integrate sdcore-amf-k8s:logging grafana-agent-k8s
```

## Screenshot
![image](https://github.com/canonical/sdcore-amf-k8s-operator/assets/18486508/bed74671-1dc9-4668-af24-8d03bb570898)

## Reference
- https://github.com/canonical/pebble/#layer-specification

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2024-02-28 21:04 UTC, ghislainbourgeois requested changes

2024-02-28 21:04 UTC, ghislainbourgeois commented on src/charm.py
When looking at all commits, this seems to be missing the changes to the pebble layer itself. I think there is a bad merge in your commits, because going back to previous commits I can see the change.

2024-02-28 21:17 UTC, gruyaume commented on src/charm.py
This was intentional, previously we used the v0 of the loki lib where the pebble layer had to be manipulated in the charm code. With v1 and the LogForwarder class, this is all handled by the loki lib

2024-02-29 14:56 UTC, Gmerold requested changes

2024-02-29 14:56 UTC, Gmerold commented on metadata.yaml
> +  - juju >= 3.1
```suggestion
  - juju >= 3.4
```

2024-02-29 14:57 UTC, Gmerold approved these changes

2024-02-29 15:49 UTC, merged